import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MangAlyzer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-body text-text [&>*]:w-10/12 flex flex-col flex-grow h-screen items-center`}>
        {/* Navbar */}
        <Navbar />

        {/* Active Page */}
        {children}

        <Footer />
      </body>
    </html>
  );
}
